name: CI

on:
  push:
    branches: ["main", "master", "develop"]
  pull_request:

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    name: Unit tests
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - name: Install deps
        run: npm ci

      - name: Run unit tests
        run: npm run test:run

  quality:
    name: Lint / Typecheck / Build (non-blocking)
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - name: Install deps
        run: npm ci

      #  Não bloqueia mesmo que falhe
      - name: Typecheck
        run: npm run typecheck || true

      - name: Lint
        run: npm run lint || true

      - name: Build
        run: npm run build || true